"""Initial migration

Revision ID: 9a6cdd15874e
Revises: 
Create Date: 2025-10-10 15:35:57.318204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6cdd15874e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('dubbing_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('voice_track_url', sa.String(), nullable=True),
    sa.Column('background_track_url', sa.String(), nullable=True),
    sa.Column('voice_track_duration', sa.Integer(), nullable=True),
    sa.Column('background_track_duration', sa.Integer(), nullable=True),
    sa.Column('target_languages', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dubbing_jobs_id'), 'dubbing_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_dubbing_jobs_status'), 'dubbing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_dubbing_jobs_user_id'), 'dubbing_jobs', ['user_id'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['dubbing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_events_event_type'), 'job_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_job_events_id'), 'job_events', ['id'], unique=False)
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('language_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('transcript_url', sa.String(), nullable=True),
    sa.Column('translated_transcript_url', sa.String(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('captions_url', sa.String(), nullable=True),
    sa.Column('transcript_duration', sa.Integer(), nullable=True),
    sa.Column('audio_duration', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['dubbing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_tasks_id'), 'language_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_language_tasks_job_id'), 'language_tasks', ['job_id'], unique=False)
    op.create_index(op.f('ix_language_tasks_language_code'), 'language_tasks', ['language_code'], unique=False)
    op.create_index(op.f('ix_language_tasks_status'), 'language_tasks', ['status'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('language_task_id', sa.String(), nullable=True),
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['dubbing_jobs.id'], ),
    sa.ForeignKeyConstraint(['language_task_id'], ['language_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_artifact_type'), 'artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_artifacts_id'), 'artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_artifacts_job_id'), 'artifacts', ['job_id'], unique=False)
    op.create_index(op.f('ix_artifacts_language_task_id'), 'artifacts', ['language_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_language_task_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_job_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_artifact_type'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_language_tasks_status'), table_name='language_tasks')
    op.drop_index(op.f('ix_language_tasks_language_code'), table_name='language_tasks')
    op.drop_index(op.f('ix_language_tasks_job_id'), table_name='language_tasks')
    op.drop_index(op.f('ix_language_tasks_id'), table_name='language_tasks')
    op.drop_table('language_tasks')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_index(op.f('ix_job_events_id'), table_name='job_events')
    op.drop_index(op.f('ix_job_events_event_type'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_dubbing_jobs_user_id'), table_name='dubbing_jobs')
    op.drop_index(op.f('ix_dubbing_jobs_status'), table_name='dubbing_jobs')
    op.drop_index(op.f('ix_dubbing_jobs_id'), table_name='dubbing_jobs')
    op.drop_table('dubbing_jobs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
